title: musana.engineering
description: > # this means to ignore newlines until "baseurl:"
  Technical recipies curated by Jim Musana
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://musana.engineering" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jim Musana # add your name
author-img: jim-musana.jpg # add your photo
about-author: Curating Technical recipies on cloud-native technologies. Passionate about Platform Engineering, Kubernetes and the Cloud
social-twitter: musana_eng
#social-facebook: # add your Facebook handle
social-github: musana-engineering
social-linkedin: www.linkedin.com/in/jmusana
social-email: musanajim@gmail.com

# Disqus
discus-identifier: musana.engineering

comments:
  giscus:
    enabled: true
    repo: "musana-engineering/musana.engineering.github.io"
    repo_id: "R_kgDOMAlDfA"
    category: "blog-posts"
    category_id: "DIC_kwDOMAlDfM4CgIr4"
    mapping: "pathname"
    reactions_enabled: "1"
    theme: "light"

# Tracker
analytics: G-64FMGRY5TN # Google Analytics
#google_analytics: G-64FMGRY5TN

# Build Settings
markdown: kramdown
highlighter: 
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

